<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c40bcda93ed925517e6aa9eef66dbef
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Fxp\\Composer\\AssetPlugin\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Fxp\\Composer\\AssetPlugin\\' => 
        array (
            0 => __DIR__ . '/..' . '/fxp/composer-asset-plugin',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInit9c40bcda93ed925517e6aa9eef66dbef' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Composer\\Autoload\\ComposerStaticInit9c40bcda93ed925517e6aa9eef66dbef' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'Fxp\\Composer\\AssetPlugin\\Assets' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Assets.php',
        'Fxp\\Composer\\AssetPlugin\\Composer\\ScriptHandler' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Composer/ScriptHandler.php',
        'Fxp\\Composer\\AssetPlugin\\Config\\Config' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Config/Config.php',
        'Fxp\\Composer\\AssetPlugin\\Config\\ConfigBuilder' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Config/ConfigBuilder.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\AbstractPackageConverter' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/AbstractPackageConverter.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\BowerPackageConverter' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/BowerPackageConverter.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\NpmPackageConverter' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/NpmPackageConverter.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\NpmPackageUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/NpmPackageUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\PackageConverterInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/PackageConverterInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\PackageUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/PackageUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\SemverConverter' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/SemverConverter.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\SemverRangeUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/SemverRangeUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\SemverUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/SemverUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Converter\\VersionConverterInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Converter/VersionConverterInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Exception/ExceptionInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Exception/InvalidArgumentException.php',
        'Fxp\\Composer\\AssetPlugin\\Exception\\InvalidCreateRepositoryException' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Exception/InvalidCreateRepositoryException.php',
        'Fxp\\Composer\\AssetPlugin\\FxpAssetPlugin' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/FxpAssetPlugin.php',
        'Fxp\\Composer\\AssetPlugin\\Installer\\AssetInstaller' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Installer/AssetInstaller.php',
        'Fxp\\Composer\\AssetPlugin\\Installer\\BowerInstaller' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Installer/BowerInstaller.php',
        'Fxp\\Composer\\AssetPlugin\\Installer\\IgnoreFactory' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Installer/IgnoreFactory.php',
        'Fxp\\Composer\\AssetPlugin\\Installer\\IgnoreManager' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Installer/IgnoreManager.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\AbstractLazyCompletePackage' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/AbstractLazyCompletePackage.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\LazyCompletePackage' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/LazyCompletePackage.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\LazyPackageInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/LazyPackageInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\Loader\\LazyAssetPackageLoader' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/Loader/LazyAssetPackageLoader.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\Loader\\LazyLoaderInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/Loader/LazyLoaderInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Package\\Version\\VersionParser' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Package/Version/VersionParser.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\AbstractAssetVcsRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/AbstractAssetVcsRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\AbstractAssetsRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\AssetRepositoryManager' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/AssetRepositoryManager.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\AssetVcsRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\BowerPrivateRegistryFactory' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/BowerPrivateRegistryFactory.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\BowerPrivateRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/BowerPrivateRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\BowerRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/BowerRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\DefaultRegistryFactory' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/DefaultRegistryFactory.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\FilterUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/FilterUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\NpmRepository' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/NpmRepository.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\RegistryFactoryInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/RegistryFactoryInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\ResolutionManager' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/ResolutionManager.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Util' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Util.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\VcsPackageFilter' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\AbstractGitHubDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/AbstractGitHubDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\BitbucketUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/BitbucketUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\GitBitbucketDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/GitBitbucketDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\GitDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/GitDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\GitHubDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/GitHubDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\HgBitbucketDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/HgBitbucketDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\HgDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/HgDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\PerforceDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/PerforceDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\ProcessUtil' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/ProcessUtil.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\SvnDriver' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/SvnDriver.php',
        'Fxp\\Composer\\AssetPlugin\\Repository\\Vcs\\Util' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Repository/Vcs/Util.php',
        'Fxp\\Composer\\AssetPlugin\\Type\\AbstractAssetType' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Type/AbstractAssetType.php',
        'Fxp\\Composer\\AssetPlugin\\Type\\AssetTypeInterface' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Type/AssetTypeInterface.php',
        'Fxp\\Composer\\AssetPlugin\\Type\\BowerAssetType' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Type/BowerAssetType.php',
        'Fxp\\Composer\\AssetPlugin\\Type\\NpmAssetType' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Type/NpmAssetType.php',
        'Fxp\\Composer\\AssetPlugin\\Util\\AssetPlugin' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Util/AssetPlugin.php',
        'Fxp\\Composer\\AssetPlugin\\Util\\Perforce' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Util/Perforce.php',
        'Fxp\\Composer\\AssetPlugin\\Util\\Validator' => __DIR__ . '/..' . '/fxp/composer-asset-plugin/Util/Validator.php',
        'app\\controllers\\AppController' => __DIR__ . '/../..' . '/controllers/AppController.php',
        'app\\controllers\\UserController' => __DIR__ . '/../..' . '/controllers/UserController.php',
        'app\\core\\App' => __DIR__ . '/../..' . '/core/App.php',
        'app\\core\\Request' => __DIR__ . '/../..' . '/core/Request.php',
        'app\\core\\Router' => __DIR__ . '/../..' . '/core/Router.php',
        'app\\core\\database\\Connection' => __DIR__ . '/../..' . '/core/database/Connection.php',
        'app\\core\\database\\QueryBuilder' => __DIR__ . '/../..' . '/core/database/QueryBuilder.php',
        'app\\models\\Task' => __DIR__ . '/../..' . '/models/Task.php',
        'app\\models\\User' => __DIR__ . '/../..' . '/models/User.php',
        'app\\models\\base\\Model' => __DIR__ . '/../..' . '/models/base/Model.php',
        'app\\models\\pagination\\Button' => __DIR__ . '/../..' . '/models/pagination/Button.php',
        'app\\models\\pagination\\Pagination' => __DIR__ . '/../..' . '/models/pagination/Pagination.php',
        'app\\models\\sort\\Sort' => __DIR__ . '/../..' . '/models/sort/Sort.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c40bcda93ed925517e6aa9eef66dbef::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c40bcda93ed925517e6aa9eef66dbef::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9c40bcda93ed925517e6aa9eef66dbef::$classMap;

        }, null, ClassLoader::class);
    }
}
